### ISSUE TITLE
PIU XX 1.01.0 songs

### ISSUE THREAD

**Issue by Poliwrath** [pugkung/piutool#2]
Teaser: https://www.youtube.com/watch?v=bHPDfCbVQrM

(update is already released, chart videos are on the YouTube channel: https://www.youtube.com/channel/UC1zVbfSZSKz9r2AzF50l9sA/videos)

**Comment by pugkung** [comment]
songlist has been updated. f35eefdc009a4aaa1b6c0cb4239cd10100ac883a
